2023-11-05 21:39:57,519 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-05 21:40:17,417 ERROR libqtile manager.py:process_key_event():L453 KB command error toggle_floating: No object window in path 'window'
2023-11-05 21:40:18,226 ERROR libqtile manager.py:process_key_event():L453 KB command error toggle_floating: No object window in path 'window'
2023-11-05 21:40:19,447 ERROR libqtile manager.py:process_key_event():L453 KB command error toggle_floating: No object window in path 'window'
2023-11-05 21:40:20,709 ERROR libqtile manager.py:process_key_event():L453 KB command error toggle_floating: No object window in path 'window'
2023-11-05 21:40:21,560 ERROR libqtile manager.py:process_key_event():L453 KB command error toggle_floating: No object window in path 'window'
2023-11-05 21:40:23,409 ERROR libqtile manager.py:process_key_event():L453 KB command error toggle_floating: No object window in path 'window'
2023-11-05 21:49:04,735 ERROR libqtile manager.py:spawn():L1252 couldn't find `fire`
2023-11-05 21:54:52,198 ERROR libqtile xcbq.py:paint():L665 Could not load wallpaper:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 662, in paint
    with open(image_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/your/primary/monitor/wallpaper'
2023-11-05 21:54:52,249 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-05 21:55:21,121 ERROR libqtile xcbq.py:paint():L665 Could not load wallpaper:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 662, in paint
    with open(image_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/your/primary/monitor/wallpaper'
2023-11-05 21:55:21,159 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-05 21:55:25,513 ERROR libqtile xcbq.py:paint():L665 Could not load wallpaper:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/xcbq.py", line 662, in paint
    with open(image_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/your/primary/monitor/wallpaper'
2023-11-05 21:55:25,550 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-05 21:55:28,950 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-05 21:58:11,814 WARNING libqtile core.py:graceful_shutdown():L908 Server disconnected, couldn't close windows gracefully.
2023-11-05 21:58:11,816 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2023-11-06 10:17:40,918 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:18:03,473 ERROR libqtile manager.py:process_key_event():L453 KB command error toggle_floating: No object window in path 'window'
2023-11-06 10:20:15,278 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 115, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:20:15,279 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:20:16,297 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 115, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:20:16,297 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:20:38,300 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 115, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:20:38,301 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:20:50,667 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 115, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:20:50,667 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:20:52,892 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 115, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:20:52,893 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:20:59,770 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 116, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:20:59,770 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:21:14,384 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2023-11-06 10:21:19,176 ERROR libqtile manager.py:load_config():L116 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 113, in load_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 116, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:21:19,177 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:21:19,215 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:22:18,499 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:22:24,348 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:22:27,120 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:23:14,498 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:14,498 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:16,879 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:16,880 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:17,402 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:17,402 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:17,615 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:17,615 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:21,073 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 132, in load
    config = importlib.reload(sys.modules[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:21,074 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:25,487 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2023-11-06 10:23:29,691 ERROR libqtile manager.py:load_config():L116 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 113, in load_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:29,691 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:29,730 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:23:41,048 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:41,049 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:41,709 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:41,709 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:41,749 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:41,749 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:41,788 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:41,789 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:41,829 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:41,830 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:41,869 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:41,869 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:41,909 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:41,910 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:41,950 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:41,951 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:41,990 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:41,991 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:42,030 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:42,031 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:42,071 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:42,072 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:42,111 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:42,111 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:42,150 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:42,151 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:42,191 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:42,191 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:42,231 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:42,232 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:23:42,271 ERROR libqtile manager.py:reload_config():L286 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 284, in reload_config
    self.config.load()
  File "/usr/lib/python3.11/site-packages/libqtile/confreader.py", line 134, in load
    config = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bocchi/.config/qtile/config.py", line 7, in <module>
    @hook.subscribe.startup_once
     ^^^^
NameError: name 'hook' is not defined
2023-11-06 10:23:42,271 WARNING libqtile utils.py:send_notification():L280 dbus-next is not installed. Unable to send notifications.
2023-11-06 10:24:23,574 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:24:49,742 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:24:51,359 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2023-11-06 10:24:54,928 ERROR libqtile hook.py:fire():L903 Error in hook startup_once
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/hook.py", line 901, in fire
    i(*args, **kwargs)
  File "/home/bocchi/.config/qtile/config.py", line 10, in autostart
    xrandr_setup()
  File "/home/bocchi/.config/qtile/config.py", line 13, in xrandr_setup
    subprocess.run([
    ^^^^^^^^^^
NameError: name 'subprocess' is not defined
2023-11-06 10:24:54,930 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:30:01,431 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:30:06,332 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2023-11-06 10:30:10,115 ERROR libqtile hook.py:fire():L903 Error in hook startup_once
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/hook.py", line 901, in fire
    i(*args, **kwargs)
  File "/home/bocchi/.config/qtile/config.py", line 10, in autostart
    subprocess.call([
    ^^^^^^^^^^
NameError: name 'subprocess' is not defined
2023-11-06 10:30:10,116 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:31,540 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:33,663 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:34,429 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:34,737 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:35,303 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:35,717 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:36,083 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:36,400 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:36,845 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:37,246 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:37,698 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:31:40,406 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:32:03,743 ERROR libqtile core.py:__init__():L104 not starting; existing window manager LG3D
2023-11-06 10:33:12,947 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2023-11-06 10:33:45,874 ERROR libqtile hook.py:fire():L903 Error in hook startup_once
Traceback (most recent call last):
  File "/home/bocchi/.config/qtile/config.py", line 20, in autostart
    subprocess.run(cmd, check=True)
    ^^^^^^^^^^
NameError: name 'subprocess' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/hook.py", line 901, in fire
    i(*args, **kwargs)
  File "/home/bocchi/.config/qtile/config.py", line 21, in autostart
    except subprocess.CalledProcessError as e:
           ^^^^^^^^^^
NameError: name 'subprocess' is not defined
2023-11-06 10:33:45,876 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:35:18,562 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:35:21,076 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:36:53,168 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:37:36,338 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:37:39,054 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:37:40,069 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:38:45,102 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:38:46,577 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:38:47,240 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:38:47,408 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
2023-11-06 10:38:47,575 WARNING libqtile sleep.py:start():L86 dbus-next is not installed. Cannot run inhibitor process.
